version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: defi_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: defi
      POSTGRES_PASSWORD: 2fe!!.iufh_=153fds1s4
      POSTGRES_DB: defi_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
